#!/bin/sh
module="physicalmemory"
device="physicalmemory"
mode="666"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod -f ./$module.ko $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's physicalmemory that has several devices in it.

rm -f /dev/${device}
mknod /dev/${device} c $major 0
# mknod /dev/${device}n c $major 1
chgrp $group /dev/${device} 
chmod $mode  /dev/${device}
